stages:
  - test
  - build
  - deploy-test
  - deploy-prod

variables:
  DOCKER_REGISTRY: registry.example.com
  PROJECT_NAME: web-calculator
  BLUE_TAG: "blue-${CI_COMMIT_SHORT_SHA}"
  GREEN_TAG: "green-${CI_COMMIT_SHORT_SHA}"

# 1. 测试阶段
unit-test:
  stage: test
  image: python:3.9-alpine
  script:
    - pip install -r requirements.txt
    - pytest tests/ --cov=src --cov-report=xml
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

integration-test:
  stage: test
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker-compose -f docker-compose.test.yml up -d
    - sleep 30  # 等待服务启动
    - ./scripts/health-check.sh http://localhost:5000
    - ./run-integration-tests.sh
    - docker-compose -f docker-compose.test.yml down

# 2. 构建阶段
build-and-push:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  script:
    # 构建镜像
    - docker build -t ${DOCKER_REGISTRY}/${PROJECT_NAME}:${BLUE_TAG} .
    - docker build -t ${DOCKER_REGISTRY}/${PROJECT_NAME}:${GREEN_TAG} .
    
    # 推送镜像
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:${BLUE_TAG}
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:${GREEN_TAG}
    
    # 标记为 latest（可选）
    - docker tag ${DOCKER_REGISTRY}/${PROJECT_NAME}:${BLUE_TAG} ${DOCKER_REGISTRY}/${PROJECT_NAME}:latest
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:latest
  only:
    - main
    - develop

# 3. 测试环境部署
deploy-to-test:
  stage: deploy-test
  image: alpine
  script:
    - apk add --no-cache sshpass
    - sshpass -p ${TEST_SERVER_PASSWORD} ssh -o StrictHostKeyChecking=no ${TEST_SERVER_USER}@${TEST_SERVER_IP} "
        cd /opt/${PROJECT_NAME} &&
        export BLUE_TAG=${BLUE_TAG} &&
        export GREEN_TAG=${GREEN_TAG} &&
        docker-compose pull &&
        ./scripts/switch-traffic.sh green &&
        docker system prune -f
      "
  environment:
    name: test
    url: http://test.example.com
  only:
    - develop

# 4. 生产环境部署（手动触发）
deploy-to-production:
  stage: deploy-prod
  image: alpine
  script:
    - apk add --no-cache sshpass
    - sshpass -p ${PROD_SERVER_PASSWORD} ssh -o StrictHostKeyChecking=no ${PROD_SERVER_USER}@${PROD_SERVER_IP} "
        cd /opt/${PROJECT_NAME} &&
        export BLUE_TAG=${BLUE_TAG} &&
        export GREEN_TAG=${GREEN_TAG} &&
        docker-compose pull &&
        ./scripts/deploy.sh
      "
  environment:
    name: production
    url: http://production.example.com
  when: manual  # 手动触发部署
  only:
    - main